title: Voravich Chaturavichanan
logo: /images/new_profile.jpg
description: 🧠 Graduate student in Economics with experience at the intersection of economics, data science, and financial stability
theme: jekyll-theme-minimal
